### ISSUE TITLE
Cache push fails because of TypeError

### ISSUE THREAD

**Issue by ners** [ryanccn/attic-action#17]
https://github.com/ners/trilby/actions/runs/7336472695/job/19976258464

```
Post Run ryanccn/attic-action@v0

Post job cleanup.
Push to Attic
  Pushing to cache
  Warning: Action encountered error: TypeError: JSON.parse(...).map is not a function
  Not considering errors during push a failure.
```

**Comment by getchoo** [comment]
this is due to nix v2.19 changing the json output of `path-info`. i would recommend using 2.18.1 for now, which is the default in nixpkgs-unstable
