### ISSUE TITLE
Proposal: Skip installation when `attic` in `PATH`

### ISSUE THREAD

**Issue by pfzetto** [ryanccn/attic-action#20]
Hello,
I'm currently trying to use this action on a "host"-runner. 
Sadly the installation of `attic` using the script doesn't work, but I can add `attic` to the PATH using the provided flake.

It would be nice if the action would skip the attic installation if the binary is already present.

What do you think? I would be happy to implement the feature if you are ok with it.

**Comment by ryanccn** [comment]
I think that's a very good idea :+1:
