### ISSUE TITLE
Feed paths via stdin

### ISSUE THREAD

**Issue by jzbor** [ryanccn/attic-action#27]
It is now possible to feed attic paths via stdin: https://github.com/zhaofengli/attic/pull/176

This way it is no longer to chunk the paths when pushing (https://github.com/ryanccn/attic-action/blob/5619ef4781449b8774693be0a37f01d38a024bde/src/stages/push.ts#L29).
This should significantly speed up the action.

**Comment by ryanccn** [comment]
This is blocked until Nixpkgs' `attic-client` is updated to include this feature, since it is not feasible to build attic from source on every CI run.

**Comment by jzbor** [comment]
Alright! Seems like the corresponding PR is already on master, so it should not be too long: https://github.com/NixOS/nixpkgs/pull/346503
